import numpy as np
import heartpy as hp
from scipy.signal import resample
from scipy.interpolate import interp1d
import os

def estimate_hr_heartpy(segment, fs):
    """
    Estimates Heart Rate (HR) from a signal segment using HeartPy.
    Returns NaN if the process fails.
    """
    try:
        wd, m = hp.process(segment, sample_rate=fs)
        hr_value = m['bpm']
        return hr_value
    except Exception:
        return np.nan

def save_hr_from_ecg():
    # =========================
    # Configuration
    # =========================
    # Path to the CSV file generated by opengtmat.py
    input_csv = r"C:\Users\Sophia\Documents\rPPG\get_ground_truth\ECG\vinicius_video004_ecg.csv"
    output_txt = r"C:\Users\Sophia\Documents\rPPG\get_ground_truth\ECG\vinicius_video004_ecg.txt"
    
    fs = 1000       # Sample rate of the input ECG (e.g., 1000 Hz)
    n_points = 6000  # Target number of points for the output (to match video duration/frames)
    window_sec = 15  # Sliding window size in seconds
    step_sec = 1     # Step size in seconds

    if not os.path.exists(input_csv):
        print(f"Error: Input file not found at {input_csv}")
        return

    # =========================
    # Data Loading
    # =========================
    print(f"Loading ECG data from: {input_csv}")
    # hp.get_data reads the CSV into a 1D numpy array
    sig = hp.get_data(input_csv)
    
    total_samples = len(sig)
    duration = total_samples / fs
    t_rel = np.arange(total_samples) / fs

    # =========================
    # Processing
    # =========================
    # 1. Resample ECG Signal (Line 1 of output)
    print(f"Resampling signal to {n_points} points...")
    ecg_resampled = resample(sig, n_points)

    # 2. Calculate Timesteps for resampled length (Line 3 of output)
    t_new = np.linspace(t_rel[0], t_rel[-1], n_points)

    # 3. Calculate HR Estimates (Line 2 of output)
    print("Calculating HR using HeartPy sliding window...")
    window_len = int(window_sec * fs)
    step_len = int(step_sec * fs)

    hr_times = []
    hr_values = []

    for i in range(0, total_samples - window_len, step_len):
        segment = sig[i : i + window_len]
        hr = estimate_hr_heartpy(segment, fs)
        hr_values.append(hr)
        # Time point for HR is the center of the window
        hr_times.append(t_rel[i + window_len // 2])

    # Interpolate calculated HR values to match the resampled signal length
    hr_times = np.array(hr_times)
    hr_values = np.array(hr_values)
    valid_mask = ~np.isnan(hr_values)

    if np.sum(valid_mask) > 1:
        f_hr = interp1d(hr_times[valid_mask], hr_values[valid_mask], kind='linear', fill_value="extrapolate")
        hr_resampled = f_hr(t_new)
    else:
        print("Warning: Not enough valid HR values found. Filling with NaN.")
        hr_resampled = np.full(n_points, np.nan)

    # =========================
    # Saving
    # =========================
    # Save to file: Line 1=ECG, Line 2=HR, Line 3=Time
    data_save = np.vstack((ecg_resampled, hr_resampled, t_new))
    
    os.makedirs(os.path.dirname(output_txt), exist_ok=True)
    np.savetxt(output_txt, data_save, fmt='%.7e')
    print(f"Success! Data saved to: {output_txt}")

if __name__ == "__main__":
    save_hr_from_ecg()